CREATE TABLE IF NOT EXISTS links (
 uid TEXT PRIMARY KEY, discord_id TEXT NOT NULL UNIQUE, username TEXT NOT NULL,
 share INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS oauth_nonces (nonce TEXT PRIMARY KEY, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS oauth_states (state TEXT PRIMARY KEY, nonce TEXT NOT NULL, uid TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS guilds (guild_id TEXT PRIMARY KEY, group_id TEXT NOT NULL, configured_by TEXT NOT NULL, channel_id TEXT, weekly INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS recaps (guild_id TEXT NOT NULL, week TEXT NOT NULL, status TEXT NOT NULL, PRIMARY KEY(guild_id,week));
CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY, expires INTEGER NOT NULL);
